apiVersion: v1
kind: Namespace
metadata:
  name: mealie
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: mealie
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mealie
    app.kubernetes.io/version: v3.16.0
    helm.sh/chart: mealie-0.0.1-nightly.50
  name: mealie
  namespace: mealie
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mealie
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mealie
    app.kubernetes.io/version: v3.16.0
    helm.sh/chart: mealie-0.0.1-nightly.50
  name: mealie
  namespace: mealie
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: mealie
    app.kubernetes.io/name: mealie
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: mealie
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: cephfs-2026
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: mealie
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mealie
    app.kubernetes.io/version: v3.16.0
    helm.sh/chart: mealie-0.0.1-nightly.50
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mealie
      app.kubernetes.io/name: mealie
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mealie
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mealie
        app.kubernetes.io/version: v3.16.0
        helm.sh/chart: mealie-0.0.1-nightly.50
    spec:
      containers:
      - env: null
        image: ghcr.io/mealie-recipes/mealie:v3.16.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: mealie
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext: {}
        volumeMounts:
        - mountPath: /app/data
          name: data
      securityContext: {}
      serviceAccountName: mealie
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mealie-data
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mealie-backup
  namespace: mealie
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - |
              restic snapshots &>/dev/null || restic init
              restic backup /data
              restic forget --keep-daily 7 --keep-weekly 4 --keep-monthly 3 --prune
            env:
            - name: RESTIC_REPOSITORY
              value: s3:http://garage.irminsul:3900/mealie-backups/restic
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  key: aws-region
                  name: s3-backup-restic
            - name: RESTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: restic-password
                  name: s3-backup-restic
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws-access-key-id
                  name: s3-backup-restic
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws-secret-access-key
                  name: s3-backup-restic
            image: restic/restic:latest
            name: restic
            volumeMounts:
            - mountPath: /data
              name: data
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: mealie-data
  schedule: 0 2 * * *
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-restic
  namespace: mealie
spec:
  data:
  - remoteRef:
      key: kv/nekropolis/mealie/s3-backup-restic
      property: restic-password
    secretKey: restic-password
  - remoteRef:
      key: kv/nekropolis/mealie/s3-backup-restic
      property: aws-access-key-id
    secretKey: aws-access-key-id
  - remoteRef:
      key: kv/nekropolis/mealie/s3-backup-restic
      property: aws-secret-access-key
    secretKey: aws-secret-access-key
  - remoteRef:
      key: kv/nekropolis/mealie/s3-backup-restic
      property: region
    secretKey: aws-region
  refreshInterval: 1h0m0s
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: s3-backup-credentials
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: local-ca-issuer
    kube-vip.io/loadbalancerIPs: 192.168.13.12
  name: mealie
  namespace: mealie
spec:
  ingressClassName: cilium
  rules:
  - host: mealie.nekropolis.irminsul
    http:
      paths:
      - backend:
          service:
            name: mealie
            port:
              number: 9000
        path: /
        pathType: Prefix
  - host: mealie.irminsul
    http:
      paths:
      - backend:
          service:
            name: mealie
            port:
              number: 9000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mealie.irminsul
    - mealie.nekropolis.irminsul
    secretName: mealie-certificate
