apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-restic
spec:
  data:
    - secretKey: restic-password
      remoteRef:
        key: kv/nekropolis/mealie/s3-backup-restic
        property: restic-password
    - secretKey: aws-access-key-id
      remoteRef:
        key: kv/nekropolis/mealie/s3-backup-restic
        property: aws-access-key-id
    - secretKey: aws-secret-access-key
      remoteRef:
        key: kv/nekropolis/mealie/s3-backup-restic
        property: aws-secret-access-key
    - secretKey: aws-region
      remoteRef:
        key: kv/nekropolis/mealie/s3-backup-restic
        property: aws-region
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: s3-backup-credentials
  refreshPolicy: Periodic
  refreshInterval: 1h0m0s

